baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Marco's Webpage"
theme = 'odlot'
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2